the-scouts/incognita

- .readthedocs.yml
- README.md
- docs/requirements-docs.txt
- setup.py
- src/ONS_data.py
- src/ONS_data_May_16.py
- src/ONS_data_May_18.py
- src/census_merge_postcode.py
- src/scout_map.py
- src/script_handler.py
- src/scripts/add_ons_data_script.py
- src/scripts/filter_records.py
- src/scripts/group_history_IMD_script.py
- src/scripts/group_history_YUF_script.py
- src/scripts/group_summary.py
- src/scripts/opened_sections_history.py
- src/scripts/section_history.py
- src/scripts/section_mapping_script.py
- src/scripts/uptake_script.py
- src/scripts/west_yorkshire_lsoas.py
Removes geo_scout references from all files in project
- Changes to Implicit Namespace Packages for importing - base src
- Changes README.md for new project name
- Changes docs to use setup_tools and remove references
> removed geo_scout references

- src/ONS_data.py
- src/ONS_data_May_18.py
- src/ONS_data_May_19.py
- src/census_data.py
- src/census_merge_postcode.py
- src/choropleth.py
- src/log_util.py
- src/scout_map.py
- src/script_handler.py
Adds documentation to all maor classes and files, and extends inline documentation etc. in other places.
Would appreciate a sense check before merging @ox-baloo?
I would propose merging by Friday 23:59
> Extend documentation

- src/census_merge_postcode.py
- src/scout_map.py
- separate merge and postcode clean functions
- add cleaned postcode column as separate to original postcode column
- insert valid postcode and clean postcode columns next to original
postcode column
- improved postcode verification process - now matches against ONS
Postcode Directory instead of custom regex
- removed now unused regular expression
> Improve postcode cleaning and merging

- src/scout_map.py
- src/scripts/settings.json
- src/scripts/uk_imd_report.py
- Adds IMD Decile as a Boundary so reports can be made collating by IMD
Decile scores.
> IMD Decile as Boundary

- src/ONS_data.py
- src/choropleth.py
- src/scout_map.py
- src/script_handler.py
- src/scripts/county_imd_map.py
Improving ouptut of county imd map script, which produces a map with the lsoa's of the county coloured by IMD and Sections on top.
Enabled adding of surrounding areas and colour their sections gray. This is not yet automatic to work out what the neighbouring districts are, but is a step towards it.
If section markers are added fits the initial opening of the map to this area
Added ability to choose whether to have a cluster marker layer or a marker layer
Please feel free to amend or discuss - my style is probably not amazing/has flaws
> Mapping between ons fields

- setup.py
- src/census_data.py
- src/census_merge_postcode.py
- src/scout_map.py
Adds new method and logic to fix large amount of invalid postcodes
Resolves #9.
Invalid postcodes now make up 0.94% of young-people-containing entities, an 18x reduction.
Uses apply, multi-level indexing, xs and query. 
Please let me know thoughts - I've been doing this for 9.5 hours now so thoughts may not be the most coherent :p
> Fix invalid postcodes

- src/census_merge_postcode.py
In a commit a while ago I put in dropna which filtered out too many postcodes
Fixed locally a while ago but now pushing to master.
> Fix error file

- src/ONS_data.py
Simple update to refactor method to one line and remove dual indexing
> Removed double indexing

- src/scout_map.py
Minor updates including using dummy variables to refer to np.NAN, fixing a logic error due to the changes in the boundary report, and making a test more explicit (and possibly quicker)
> Minor updates to create_uptake_report()

- src/ONS_data_May_19.py
- src/scout_map.py
- src/scripts/young_person_uk_map.py
Update to section maps function to allow Section numbers as well as uptake percentages to be plotted.
Also updates some of the Shapefiles for the May 2019 ONS PD to the correct ones.
> Section maps and shapefiles

- src/base.py
- src/boundary.py
- src/history_summary.py
- src/map.py
- src/map_plotter.py
- src/ons_pd.py
- src/scout_data.py
- src/scripts/settings.json
- src/scripts/uptake_script.py
- src/scripts/west_yorkshire_lsoas.py
Producing county maps for systematic release
Thought I'd explain what it was doing - not quite ready to be merged, need to self-review first, but feel free to have a look and explore and see what you think.
Idea is to present Sections that are close to the county in gray, interested in your thoughts @AA-Turner ? - run uptake_script.py and see what you think?
> Developing county uptake maps

- .gitignore
- application.py
- settings.json
- src/boundary.py
- src/dashboard.py
- src/log_util.py
- src/map.py
- src/map_plotter.py
- src/scripts/uptake_with_imd_script.py
- src/settings.json
Adds the ability to plot IMD Decile and % uptake by Westminster Parliamentary Constituency (or indeed mutliple layers of different boundaries).
Has some slight deficiencies which will need to be corrected, notably between boundary, map_plotter and map, where the readibility and functionallity could be improved relatively easily.
> Dash webapp

- README.md
- src/boundary.py
- src/history_summary.py
- src/map.py
- src/map_plotter.py
- src/scripts/section_history.py
- src/scripts/uptake_with_imd_script.py
This should make it easier to add multiple area colourings (e.g. IMD decile and % uptake by pcon) to the same map.
Also new found love of decorators, in particular the @property, which makes the function look like a variable, but necessarily obfuscates the dictionary (which was getting confusing ...)
> Simplify boundaries

- scripts/map_add_custom_data.py
- scripts/map_west_yorkshire_lsoas.py
- scripts/settings.json
- scripts/setup_data_file.py
- scripts/setup_reduce_onspd.py
- src/data/ons_pd.py
- src/data/ons_pd_may_19.py
- src/data/scout_data.py
As discussed on the call - support both the large file for merging and the small file for lookups/mapping
> Add reduced and full ONS PD options

- scripts/setup_data_file.py
- src/data/census_merge_data.py
- src/data/scout_census.py
- src/data/scout_data.py
- src/maps/map.py
- src/reports/history_summary.py
- src/reports/reports.py
- src/utility.py
Adds support for 2020 Census extract. 
By merging this branch we will drop support for 2019 Census extracts
> Census 2020

- scripts/setup_data_file.py
- src/data/scout_census.py
> Relocate magic strings to ScoutCensus

- scripts/history_group_history_IMD_script.py
- scripts/history_group_history_YUF_script.py
- scripts/history_opened_sections_history.py
- scripts/history_section_history.py
- scripts/history_section_mapping_script.py
- scripts/map_all_uptake_script.py
- scripts/map_county_imd_map.py
- scripts/map_west_yorkshire_lsoas.py
- scripts/reports_uk_imd_report.py
- scripts/settings.json
- scripts/setup_data_file.py
- scripts/setup_reduce_onspd.py
- src/data/ons_pd_may_19.py
- src/data/scout_data.py
- src/reports/reports.py
- tests/test_scout_data.py
- tests/test_utility.py
> Fix IMD deciles on LSOA reports

- environment.yml
- scripts/map_add_custom_data.py
- scripts/map_imd_uk.py
- scripts/map_uptake_script.py
- scripts/settings.json
- scripts/setup_data_file.py
- setup.py
- src/base.py
- src/data/census_merge_data.py
- src/data/ons_pd.py
- src/data/ons_pd_may_19.py
- src/data/scout_census.py
- src/data/scout_data.py
- src/geographies/district_boundaries.py
- src/geographies/geography.py
- src/log_util.py
- src/maps/map.py
- src/maps/map_plotter.py
- src/reports/history_summary.py
- src/reports/reports.py
- src/utility.py
Supports feather for data storage and retrieval - took a script from 30s to 10s on my PC
> Efficiencies

- scripts/settings.json
- scripts/setup_data_file.py
- scripts/setup_reduce_onspd.py
- src/data/ons_pd_may_18.py
- src/data/ons_pd_may_19.py
- src/data/scout_data.py
- src/maps/map.py
- src/maps/map_plotter.py
- src/reports/reports.py
- src/utility.py
Increase speed of add_meeting_places_to_map 7x
> Update map plotting

- src/geographies/district_boundaries.py
- src/geographies/geography.py
- src/maps/map.py
- src/maps/map_plotter.py
The ongoing quest to remove magic values continues... will merge this now as no major code changes but welcome thoughts if you've any @ox-baloo
> Move CRS values away from magic strings

- src/incognita/preprocessing/census_merge_data.py
- src/incognita/preprocessing/setup_data_file.py
Prior: 157s
Now: 28.73s
Around a 5.5x speedup, and miscellaneous refactoring.
> Increase census extract processing speeds

- environment-test.yml
- environment.yml
- requirements-run.txt
- scripts/map_add_custom_data.py
- scripts/map_awards_script.py
- scripts/map_heatmap_county_growth.py
- scripts/map_imd_uk.py
- scripts/map_uptake_script.py
- scripts/map_west_yorkshire_lsoas.py
- scripts/map_young_person_uk_map.py
- scripts/reports_uk_imd_report.py
- src/incognita/geographies/district_boundaries.py
- src/incognita/maps/map.py
- src/incognita/reports/history_summary.py
Having usable / semi-realistic district boundaries would be useful, so might as well make it fast.
Three potential methods:
- Current circle point buffers (slow)
- Potentially use Voronoi diagrams (fast but inaccurate - straight lines)
- Potentially assemble together council wards - likely to be a better representation of how Districts are actually composed
Buffer improvements alone move from ~1 hour to ~30s
> Performance - District Boundaries
